global:
  govcloud: true
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-compliance-cis-benchmark
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - us-east-1
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: main.template
  
